#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

secret_key=$(ynh_app_setting_get --app=$app --key=secret_key)
admin_mail=$(ynh_app_setting_get --app=$app --key=admin_mail)
timezone=$(ynh_app_setting_get --app=$app --key=timezone)
redis_db=$(ynh_app_setting_get --app=$app --key=redis_db)
celery_broker_db=$(ynh_app_setting_get --app=$app --key=celery_broker_db)
celery_result_db=$(ynh_app_setting_get --app=$app --key=celery_result_db)
project_name=$(ynh_app_setting_get --app=$app --key=project_name)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app-gunicorn" --action="stop"

if [ "$use_celery" -eq 1 ]; then
    ynh_systemctl --service="$app-celery" --action="stop"
    ynh_systemctl --service="$app-celery-beat" --action="stop"
    ynh_systemctl --service="$app-flower" --action="stop"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

pushd $install_dir
    extract_project $project

    if [ -f "$install_dir/.env.example" ]; then
        ynh_config_add --template="$install_dir/.env.example" --destination="$install_dir/.env"
    else
        
        if [ "$db_engine" = "postgresql" ]; then
            ynh_config_add --template=".env" --destination="$install_dir/.env"
        
        elif [ "$db_engine" = "sqlite" ]; then
            ynh_config_add --template=".env.sqlite" --destination="$install_dir/.env"
        fi
    
    fi

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"
 
    source venv/bin/activate
    pip install --upgrade -r requirements.txt
    python manage.py migrate
    python manage.py collectstatic --noinput
    deactivate
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="$app-gunicorn" --template="gunicorn.service"
yunohost service add "$app-gunicorn" --description="Gunicorn for $app" --log="/var/log/$app/$app-gunicorn.log"

if [ "$use_celery" -eq 1 ]; then
    ynh_config_add_systemd --service="$app-celery" --template="celery.service"
    ynh_config_add_systemd --service="$app-celery-beat" --template="celery-beat.service"
    ynh_config_add_systemd --service="$app-flower" --template="flower.service"
    yunohost service add "$app-celery" --description="Celery for $app" --log="/var/log/$app/$app-celery.log"
    yunohost service add "$app-celery-beat" --description="Celery beat for $app" --log="/var/log/$app/$app-celery-beat.log"
    yunohost service add "$app-flower" --description="Flower for $app" --log="/var/log/$app/$app-flower.log"
fi

# Services should not be readable by other than root because credentials are in folwer service, so any user with ssh/sftp access can read them
chmod 400 /etc/systemd/system/$app*

ynh_config_add_logrotate

# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-gunicorn" --action="start"

if [ "$use_celery" -eq 1 ]; then
    ynh_systemctl --service="$app-celery" --action="start"
    ynh_systemctl --service="$app-celery-beat" --action="start"
    ynh_systemctl --service="$app-flower" --action="start"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
